### ISSUE TITLE
How to determine the algorithms

### ISSUE THREAD

**Issue by prdx** [shivayogibeeradar/Titanic#2]
@shivayogibeeradar how do you determine which algorithm to use in this case? I have read that we can use decision tree, but I am curious what else besides decision tree that we can use?

**Comment by shivayogibeeradar** [comment]
hey bagoos,
There are many methods to go about it.Onethat makes sense to me is start with correlations.
If variable are less corre;ated methods such as naive bayes work.If classes are well separated 
then methods such as lda , svm ,logistic work.For complex boundaries generally random fores and gbm are good bet.Neural nets can also be used.
